package com.spring.restful.groups.app.common;

public interface DbQueries {
	public String INSERT_GROUPS = "INSERT INTO GROUP1 (ID,NAME,STATUS,DESCRIPTION,CREATDATE,LSTMODIFIED) VALUES (GRUP_SEQ_ID.NEXTVAL,?,?,?,?,?)";
	public String GET_ALL_GROUPS = "SELECT ID, NAME, STATUS, DESCRIPTION,CREATDATE, LSTMODIFIED FROM GROUP1";
	public String GET_GROUP_BY_ID = "SELECT ID, NAME, STATUS, DESCRIPTION, CREATDATE,LSTMODIFIED FROM GROUP1 WHERE ID=?";
	public String UPDATE_GROUP_BY_ID = "UPDATE GROUP1 SET NAME =?, STATUS =?,DESCRIPTION =?, LSTMODIFIED=? WHERE ID =?";
	public String DELETE_GROUP_BY_ID = "DELETE FROM GROUP1 WHERE  ID =?";
}
